---
abstract: 'test XML with XML::Easy'
author:
  - 'Mark Fowler, C<< <mark@twoshortplanks.com> >>'
build_requires:
  Test::Builder::Tester: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-XML-Easy
no_index:
  directory:
    - inc
    - t
requires:
  XML::Easy: 0.002
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
